# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 751af72fa2ca92ce112a911026aca4d51b70e351cbc083e21f27f733d464e539b0d18f2aefe9a572235dbb05e24c0c6851a55ed7aec876af1f671bd83dcccbbd

test:
  secret_key_base: 8f62e86b686699595dcd1b4e2f280fd7bc36e37d2e35b1b9f90309f79f479df4ffe1e1bc702376d34fe36e041eb0ebad32c0113c177e633fec0ecdee38029136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
