# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c420ac68894bda3dafe859518a0121a0dcd0a882e9382db5cc2af7b936527a3c60e13d128ee211b4d146305e83a37f9f359484ec19d722519c91dc75b6571a85

test:
  secret_key_base: 8e537a7a1b973b50af7fb6352ed61f8e6b44cb9b98e2b34c5b17396f61c9b719b2f167de1a03fb38d8d633dcf771a3f2bb83155abbf9c1bb063da8924a2ec4e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
